# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0bfc74e7b814ebd37d735861663db1836c6eeea5934952b9795894763da44893745a3f17c915049dfe10adf1c4419beb0eae0e86f3a8f188c7549aa04d8e04c

test:
  secret_key_base: 9fc9c9244e1487b3458225319e99389b454bce9900a85adb0df96dc336eb5eeff2d4b2f760cb49e63045d47058eb17451c3ae91dd7a38ba77dbcf3b414e1ed09

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
